language: node_js

services:
  - docker

node_js:
  - 10

install:
  - npm install typescript

script:
  - npm run lint
  - npm run build

after_success:
  - echo "will push to docker here"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yashkumarverma/shatabdi-express .
  - docker push yashkumarverma/shatabdi-express
